version: "3"
services:
  client:
    container_name: client
    image: niflnir/client:latest
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    networks:
      - app-network
  server:
    container_name: server
    image: niflnir/server:latest
    environment:
      JWT_KEY: ${JWT_KEY}
      MONGO_URI: ${MONGO_URI}
      USER_EMAIL: ${USER_EMAIL}
      USER_PASSWORD: ${USER_PASSWORD}
      PORT: 8080
    ports:
      - 8080:8080
    networks:
      - app-network
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - client
      - server
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    command: certonly --webroot -w /var/www/certbot --force-renewal --email {email} -d {domain} -d {domain-with-www} --agree-tos
networks:
  app-network:
    driver: bridge
