name: tests-spells

on:
  pull_request:
    paths:
      - 'spells/**'

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd spells && npm install && npm run test:ci
